/* Generate data/zbll-sheets.js from the Roman-/zbll dataset (_setup/zbll-src.js).
   - Parse zbllMap[orientation][edgeConfig][caseName] = [algs].
   - Pick the first ENGINE-VERIFIED alg per case (round-trip solves + F2L preserved).
   - Group the 472 cases into the 6 corner-permutation classes (up to AUF) — "by permutation".
   - Emit 6 ALG_SETS + 6 sheet LESSONS (kind:'zbll'). Prints taxonomy + index.html lines. */
const fs = require('fs'), vm = require('vm');
const root = 'C:/AI/RubiksCubeCoach/';
const ctx = { console }; vm.createContext(ctx);
const bundle = 'const LESSONS={};' +
  ['data/notation.js', 'js/engine.js'].map(f => fs.readFileSync(root + f, 'utf8')).join('\n') +
  '\n' + fs.readFileSync(root + '_setup/zbll-src.js', 'utf8') + `
  const POS=[[1,-1,1],[-1,-1,1],[-1,-1,-1],[1,-1,-1]];
  const hi=c=>POS.findIndex(p=>p[0]===c.home.x&&p[1]===c.home.y&&p[2]===c.home.z);
  const ptype=c=>{const n=Math.abs(c.home.x)+Math.abs(c.home.y)+Math.abs(c.home.z); return n===1?'center':n===2?'edge':'corner';};
  function valid(alg){ const st=makeState(); st.reset(); st.applyTokens(invertSeq(alg));
    if(st.isSolved()) return false; let ok=true;
    st.cubies().forEach(c=>{ if(c.home.y===-1) return;
      if(ptype(c)==='center'){ if(!(c.pos.x===c.home.x&&c.pos.y===c.home.y&&c.pos.z===c.home.z)) ok=false; return; }
      if(!(c.pos.x===c.home.x&&c.pos.y===c.home.y&&c.pos.z===c.home.z&&JSON.stringify(c.ori)===JSON.stringify(I3))) ok=false; });
    st.applyTokens(tokenize(alg)); return ok && st.isSolved(); }
  function canon(alg){ const st=makeState(); st.reset(); st.applyTokens(invertSeq(alg)); let best=null;
    for(let r=0;r<4;r++){ if(r) st.applyTokens(['U']);
      const perm=POS.map(p=>{const c=st.cubies().find(cc=>cc.pos.x===p[0]&&cc.pos.y===p[1]&&cc.pos.z===p[2]); return hi(c);});
      const key=perm.join(''); if(best===null||key<best) best=key; }
    return best; }
  const ORI={H:'H',L:'L',Pi:'Pi',S:'Sune',T:'T',U:'U',aS:'Anti-Sune'};
  const out=[];
  for(const ori in zbllMap)for(const ec in zbllMap[ori])for(const cn in zbllMap[ori][ec]){
    const algs=zbllMap[ori][ec][cn]; const alg=algs.find(valid);
    if(!alg){ out.push({bad:ori+'/'+ec+'/'+cn}); continue; }
    out.push({ori:ORI[ori]||ori, key:canon(alg), moves:alg});
  }
  out;`;
const cases = vm.runInContext(bundle, ctx, { filename: 'b.js' });
const bad = cases.filter(c => c.bad);
if (bad.length) { console.error('NO VALID ALG for', bad.length, 'cases:', bad.slice(0, 5)); process.exit(1); }

// 6 corner-perm classes -> sheet ids/names
const GROUP = {
  '0123': { id: 'zbll-solved', name: 'Solved Corners', blurb: 'Last-layer corners already permuted — orient corners and place edges.' },
  '0231': { id: 'zbll-cyc-a',  name: 'Corner 3-Cycle A', blurb: 'Corners need a 3-cycle (one direction).' },
  '0312': { id: 'zbll-cyc-b',  name: 'Corner 3-Cycle B', blurb: 'Corners need a 3-cycle (the other direction).' },
  '0132': { id: 'zbll-adj-a',  name: 'Adjacent Corner Swap A', blurb: 'Two adjacent corners swap.' },
  '0213': { id: 'zbll-adj-b',  name: 'Adjacent Corner Swap B', blurb: 'Two adjacent corners swap (other pair).' },
  '0321': { id: 'zbll-diag',   name: 'Diagonal Corner Swap', blurb: 'Two diagonal corners swap.' },
};
const ORDER = ['0123', '0132', '0213', '0321', '0231', '0312'];

const sets = {}, counters = {};
ORDER.forEach(k => { sets[GROUP[k].id] = []; });
cases.forEach(c => {
  const g = GROUP[c.key]; if (!g) { console.error('unknown key', c.key); process.exit(1); }
  counters[g.id] = counters[g.id] || {}; counters[g.id][c.ori] = (counters[g.id][c.ori] || 0) + 1;
  sets[g.id].push({ name: `${c.ori} #${counters[g.id][c.ori]}`, moves: c.moves });
});

// emit data/zbll-sheets.js
let js = `/* ZBLL — 472 engine-verified last-layer algorithms (corners orientation + full permutation,
   edges pre-oriented). Algs sourced from the Roman-/zbll trainer dataset, each verified against
   the engine (round-trip solves + F2L preserved). Organized into the 6 corner-permutation subsets.
   Generated by _setup/gen-zbll.js — do not hand-edit. */\n`;
ORDER.forEach(k => {
  const g = GROUP[k];
  js += `ALG_SETS['${g.id}'] = ${JSON.stringify(sets[g.id])};\n`;
});
js += `\n`;
ORDER.forEach(k => {
  const g = GROUP[k];
  js += `LESSONS['3x3/zz/${g.id}'] = { type:'sheet', kind:'zbll', set:'${g.id}', title:'ZBLL — ${g.name}', intro:['${g.blurb} ${sets[g.id].length} cases. Each diagram shows corner orientation (top colours), the permutation (arrows), and side colours; algorithms are engine-verified.'] };\n`;
});
fs.writeFileSync(root + 'data/zbll-sheets.js', js);

console.log('Wrote data/zbll-sheets.js');
ORDER.forEach(k => console.log(`  ${GROUP[k].id.padEnd(12)} ${sets[GROUP[k].id].length} cases  (${GROUP[k].name})`));
console.log('total:', cases.length);
console.log('\n--- taxonomy items (add under 3x3 > zz method items) ---');
console.log(ORDER.map(k => `{id:'${GROUP[k].id}',name:'ZBLL — ${GROUP[k].name}'}`).join(', '));
console.log('\n--- index.html loader line (after data/algs-sheets.js) ---');
console.log(`'data/zbll-sheets.js',`);
